steps:
- checkout: microsoftgraph-docs-powershell
  clean: true
  fetchDepth: 1
  persistCredentials: true
  
- checkout: msgraph-sdk-powershell
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: self
  clean: true
  fetchDepth: 1
  