# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'PowerShellDocsUpdate Check'

parameters:
- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

resources:
 repositories:
   - repository: microsoftgraph-docs-powershell
     type: github
     endpoint: MicrosoftDocs
     name: MicrosoftDocs/microsoftgraph-docs-powershell
     ref: main

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShellDocsUpdate
  pool: 
    name: Default
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  steps:
  - template: update-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'
