# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'PowerShellDocsUpdate Check'

parameters:
- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

resources:
 repositories:
   - repository: microsoftgraph-docs-powershell
     type: github
     endpoint: timayabi2020
     name: timayabi2020/microsoftgraph-docs-powershell
     ref: main
     
   - repository: msgraph-sdk-powershell
     type: github
     endpoint: timayabi2020
     name: timayabi2020/msgraph-sdk-powershell
     ref: dev

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShellDocsUpdate
  pool: 
    name: default
    demands:
     - agent.name -equals docs
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  steps:
  - template: update-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'
      
  - task: PowerShell@2
    displayName: 'Copy files from powershell sdk'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: powershell-docs-update\scripts\FileCopy.ps1

  - task: PowerShell@2
    displayName: Pushing to github
    env:
      GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    inputs:
      targetType: inline
      script: |
        cd microsoftgraph-docs-powershell
        $date = Get-Date -Format "dd-MM-yyyy"
        $proposedBranch = "weekly_update_help_files_"+$date
        Write-Host "Checking out to " $proposedBranch
        (Get-Location).path
        git branch –-show-current
        #git checkout -f $proposedBranch
        #git status
        #git push --set-upstream origin weekly_update_help_files_15-08-2022
        #git push --set-upstream "https://${env:GITHUB_TOKEN}@github.com/timayabi2020/microsoft-docs-powershell.git"

         